# Generated by Django 6.1.1 on 2026-10-05 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name (as per PAN)')),
                ('preferred_short_name', models.CharField(blank=True, max_length=255, verbose_name='Preferred / Short Name')),
                ('fathers_spouses_name', models.CharField(max_length=255, verbose_name="Father's / Spouse's Name")),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('marital_status', models.CharField(blank=True, max_length=50, verbose_name='Marital Status')),
                ('blood_group', models.CharField(blank=True, max_length=10, verbose_name='Blood Group')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nationality')),
                ('personal_mobile_number', models.CharField(max_length=20, verbose_name='Personal Mobile No.')),
                ('alternate_mobile_number', models.CharField(blank=True, max_length=20, verbose_name='Alternate Mobile No.')),
                ('personal_email', models.EmailField(max_length=254, verbose_name='Personal Email ID')),
                ('current_address', models.CharField(max_length=255, verbose_name='Current Address (House, Street, Area)')),
                ('current_city', models.CharField(max_length=100, verbose_name='Current City')),
                ('current_state', models.CharField(max_length=100, verbose_name='Current State')),
                ('current_pin_code', models.CharField(max_length=6, verbose_name='Current PIN Code')),
                ('permanent_address_same_as_current', models.BooleanField(verbose_name='Permanent address same as current?')),
                ('permanent_address', models.CharField(blank=True, max_length=255, verbose_name='Permanent Address')),
                ('permanent_city', models.CharField(blank=True, max_length=100, verbose_name='Permanent City')),
                ('permanent_state', models.CharField(blank=True, max_length=100, verbose_name='Permanent State')),
                ('permanent_pin_code', models.CharField(blank=True, max_length=6, verbose_name='Permanent PIN Code')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Employee ID')),
                ('date_of_joining', models.DateField(verbose_name='Date of Joining')),
                ('designation', models.CharField(max_length=150, verbose_name='Designation')),
                ('department', models.CharField(max_length=150, verbose_name='Department')),
                ('employment_type', models.CharField(max_length=50, verbose_name='Employment Type')),
                ('work_location', models.CharField(max_length=255, verbose_name='Work Location')),
                ('reporting_manager', models.CharField(max_length=255, verbose_name='Reporting Manager')),
                ('official_email', models.EmailField(max_length=254, verbose_name='Official Email ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=255, verbose_name='Account Holder Name')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Bank Name')),
                ('branch', models.CharField(max_length=255, verbose_name='Branch')),
                ('account_number', models.CharField(max_length=50, verbose_name='Account Number')),
                ('account_type', models.CharField(max_length=50, verbose_name='Account Type')),
                ('ifsc_code', models.CharField(max_length=11, verbose_name='IFSC Code')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeBusinessCardDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_to_print_on_card', models.CharField(blank=True, max_length=255, verbose_name='Name to print on card')),
                ('credentials_suffix', models.CharField(blank=True, max_length=100, verbose_name='Credentials / Suffix (optional)')),
                ('designation_to_print', models.CharField(blank=True, max_length=150, verbose_name='Designation to print')),
                ('department_practice_to_print', models.CharField(blank=True, max_length=150, verbose_name='Department / Practice to print')),
                ('mobile_to_print', models.CharField(blank=True, max_length=30, verbose_name='Mobile to print')),
                ('email_to_print', models.EmailField(blank=True, max_length=254, verbose_name='Email to print')),
                ('office_landline_extension', models.CharField(blank=True, max_length=50, verbose_name='Office Landline / Extn.')),
                ('office_address_to_print', models.TextField(blank=True, verbose_name='Office Address to print')),
                ('linkedin_url', models.CharField(blank=True, max_length=255, verbose_name='LinkedIn URL (optional)')),
                ('quantity_of_cards', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Quantity of cards')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_card_details', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_confirmed', models.BooleanField(verbose_name='I confirm the above details are true and complete')),
                ('date_of_submission', models.DateField(verbose_name='Date of submission')),
                ('verified_by_hr', models.CharField(blank=True, max_length=255, verbose_name='Verified by (HR)')),
                ('verification_date', models.DateField(blank=True, null=True, verbose_name='Verification date')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaration', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocumentChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan_card_copy', models.CharField(max_length=30, verbose_name='PAN card copy')),
                ('aadhaar_card_copy', models.CharField(max_length=30, verbose_name='Aadhaar card copy')),
                ('passport_copy', models.CharField(blank=True, max_length=30, verbose_name='Passport copy')),
                ('passport_size_photograph', models.CharField(max_length=30, verbose_name='Passport-size photograph')),
                ('cancelled_cheque_bank_letter', models.CharField(max_length=30, verbose_name='Cancelled cheque / bank letter')),
                ('education_certificates', models.CharField(max_length=30, verbose_name='Education certificates')),
                ('relieving_experience_letter', models.CharField(blank=True, max_length=30, verbose_name='Relieving / experience letter')),
                ('last_three_months_payslips', models.CharField(blank=True, max_length=30, verbose_name="Last 3 months' payslips")),
                ('form_16_12b_previous_employer', models.CharField(blank=True, max_length=30, verbose_name='Form 16 / Form 12B (prev. employer)')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_checklist', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_qualification', models.CharField(max_length=255, verbose_name='Highest Qualification')),
                ('university_institute', models.CharField(blank=True, max_length=255, verbose_name='University / Institute')),
                ('year_of_completion', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year of Completion')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeEmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Contact Name')),
                ('relationship', models.CharField(max_length=50, verbose_name='Relationship')),
                ('contact_mobile_number', models.CharField(max_length=20, verbose_name='Contact Mobile No.')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(max_length=10, verbose_name='PAN')),
                ('name_as_per_pan', models.CharField(max_length=255, verbose_name='Name as per PAN')),
                ('aadhaar_number', models.CharField(max_length=12, verbose_name='Aadhaar Number')),
                ('name_as_per_aadhaar', models.CharField(max_length=255, verbose_name='Name as per Aadhaar')),
                ('passport_number', models.CharField(blank=True, max_length=50, verbose_name='Passport Number')),
                ('passport_expiry_date', models.DateField(blank=True, null=True, verbose_name='Passport Expiry Date')),
                ('voter_id_epic_number', models.CharField(blank=True, max_length=50, verbose_name='Voter ID (EPIC) No.')),
                ('driving_licence_number', models.CharField(blank=True, max_length=50, verbose_name='Driving Licence No.')),
                ('driving_licence_expiry', models.DateField(blank=True, null=True, verbose_name='Driving Licence Expiry')),
                ('uan', models.CharField(blank=True, max_length=50, verbose_name='UAN (if existing PF member)')),
                ('previous_pf_member_id', models.CharField(blank=True, max_length=100, verbose_name='Previous PF Member ID')),
                ('esic_ip_number', models.CharField(blank=True, max_length=50, verbose_name='ESIC IP Number (if any)')),
                ('previous_employer', models.CharField(blank=True, max_length=255, verbose_name='Previous Employer')),
                ('income_tax_regime_opted', models.CharField(blank=True, max_length=50, verbose_name='Income Tax Regime Opted')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to='employees.employee')),
            ],
        ),
    ]
