# Generated by Django 6.1.1 on 2026-10-05 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='current_pin_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a 6-digit PIN code.')], verbose_name='Current PIN Code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='permanent_pin_code',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a 6-digit PIN code.')], verbose_name='Permanent PIN Code'),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='ifsc_code',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^[A-Z]{4}0[A-Z0-9]{6}$')], verbose_name='IFSC Code'),
        ),
        migrations.AlterField(
            model_name='employeebusinesscarddetails',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=255, verbose_name='LinkedIn URL (optional)'),
        ),
        migrations.AlterField(
            model_name='employeekyc',
            name='aadhaar_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$')], verbose_name='Aadhaar Number'),
        ),
        migrations.AlterField(
            model_name='employeekyc',
            name='pan',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z]{5}[0-9]{4}[A-Z]$')], verbose_name='PAN'),
        ),
    ]
