# Generated by Django 6.1.1 on 2026-10-06 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_leaveapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('laptop', 'Laptop'), ('monitor', 'Monitor'), ('mobile', 'Mobile'), ('other', 'Other')], max_length=20)),
                ('asset_name', models.CharField(max_length=255)),
                ('model_series', models.CharField(blank=True, max_length=255, verbose_name='Model / Series')),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('asset_tag', models.CharField(blank=True, max_length=100)),
                ('assigned_date', models.DateField()),
                ('returned_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned')], default='assigned', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='employees.employee')),
            ],
        ),
    ]
